# Generated by Django 5.1.2 on 2024-11-29 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animal', '0002_uploadedimage_delete_animal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='animal_images/')),
                ('tags', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
