# Generated by Django 5.2.3 on 2025-06-24 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animal', '0005_injuryreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='injuryreport',
            name='image',
            field=models.ImageField(default=1, upload_to='injury_reports/'),
            preserve_default=False,
        ),
    ]
