export const videoData = [
    {
      videoId: 'LIaqKI7B8EI',  
      title: 'Minor Burn',
      channel: 'By Hadn’t',
      time: '20min', 
      rating: 5,
      type: 'Minor', 
      duration: '2 min',
      thumbnail: 'https://imgs.search.brave.com/0J65KcBCFMPbmP1PlOCuRmVAh4dL81W_-WBnP1NtTvg/rs:fit:500:0:0:0/g:ce/aHR0cHM6Ly9pLnBp/bmltZy5jb20vb3Jp/Z2luYWxzL2Q1L2Y2/LzFkL2Q1ZjYxZDNj/NzU1MWMxMmRjYmU1/OTIxY2E4ZWQzYjEx/LmpwZw',
      description: 'Learn how to treat a minor burn with simple first aid steps.',
      instructions: 'To treat a minor burn, immediately remove the source of heat and cool the burn under running cold water for 10-20 minutes. Do not use ice directly on the burn as it can cause further damage to the tissue. After cooling, cover the burn with a sterile, non-stick dressing or clean cloth to protect the area from infection. Avoid breaking blisters if they form, as this can introduce bacteria. Offer pain relief through over-the-counter medication, and if the burn is large or worsening, seek medical attention immediately.'
    },
    {
      videoId: 'PSbaUtDLHWI',  
      title: 'Minor Injury',
      channel: 'By Hadn’t',
      time: '15min',
      rating: 4,
      type: 'Minor',  
      duration: '20 min',
      thumbnail: 'https://www.shutterstock.com/image-vector/bandaging-color-icon-hurt-finger-260nw-1567029646.jpg',
      description: 'This video covers how to handle minor injuries like cuts and sprains.',
      instructions: 'For treating a cut, clean the wound gently with clean water and apply an antiseptic solution to prevent infection. Use a sterile bandage to cover the wound and ensure it stays dry. For sprains, elevate the injured area above the heart level and apply an ice pack wrapped in a cloth to reduce swelling. Avoid using heat on the sprain during the first 48 hours. Monitor for signs of infection or worsening pain and seek medical help if necessary. It is important to rest the injured area to promote faster recovery.'
    },
    {
      videoId: '5GVYiD0WzaE',  
      title: 'Severe Bleeding',
      channel: 'By Health Guide',
      time: '45min',
      rating: 5,
      type: 'Critical',  
      duration: '8 min',
      thumbnail: 'https://media.istockphoto.com/id/477827854/vector/first-aid-compression-injury-in-the-arm.jpg?s=2048x2048&w=is&k=20&c=KMAnQbI16dCWh0KR71mvsODEEzsc0awoBQaNGu3jj34=',
      description: 'Steps for controlling severe bleeding and applying pressure effectively.',
      instructions: 'In case of severe bleeding, apply direct pressure to the wound with a clean cloth or bandage to control the blood flow. If the bleeding does not stop, add more cloth on top and continue applying pressure. Keep the victim calm and still to prevent further blood loss. Elevate the bleeding limb if possible, as this can help reduce blood flow to the injured area. In the case of arterial bleeding, use a tourniquet above the wound to stop the blood flow, but only if necessary. Seek immediate medical assistance as severe bleeding can be life-threatening.'
    },
    {
      videoId: 'QllguanpKic',  
      title: 'Heart Attack First Aid',
      channel: 'By MedCare',
      time: '10min',
      rating: 5,
      type: 'Critical',
      duration: '7 min',
      thumbnail: 'https://t4.ftcdn.net/jpg/01/00/96/69/360_F_100966945_T6ZFIXRZLlv07wXPVBKpyS9Uhzp3YwQr.jpg',
      description: 'How to handle a heart attack emergency and perform CPR until help arrives.',
      instructions: 'If you suspect someone is having a heart attack, immediately call emergency services and explain the symptoms. Encourage the person to chew and swallow an aspirin, as this can help reduce the damage to the heart. If the person is unconscious and not breathing, begin CPR by performing chest compressions and rescue breaths. Continue CPR until help arrives or the person begins breathing again. If an automated external defibrillator (AED) is available, use it as soon as possible. Time is critical in a heart attack situation, so fast action can save a life.'
    },
    {
      videoId: 'SSQ_NS4VTM4',  
      title: 'Minor Cut Treatment',
      channel: 'By Quick Help',
      time: '5min',
      rating: 2, 
      type: 'Minor',  
      duration: '2 min',
      thumbnail: 'https://www.wikihow.com/images/thumb/5/5d/Treat-a-Minor-Cut-Step-1-Version-2.jpg/v4-460px-Treat-a-Minor-Cut-Step-1-Version-2.jpg.webp',
      description: 'Basic first aid steps to handle minor cuts. Not very detailed.',
      instructions: 'For minor cuts, start by cleaning the area gently with soap and water to remove any dirt. Apply an antiseptic ointment or cream to prevent infection. Bandage the cut with a sterile bandage, ensuring it is not too tight. Change the bandage daily and keep the wound dry to avoid irritation. Monitor the cut for signs of infection, such as redness or pus, and seek medical help if needed. Though simple, ensuring proper hygiene is key to a quick recovery.'
    },
    {
      videoId: 'sPzXAVNVJr0',  
      title: 'Fracture Treatment',
      channel: 'By First Aid Pro',
      time: '30min',
      rating: 4,
      type: 'Medium',  
      duration: '10 min',
      thumbnail: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR-X7tW-_kQR-4eXya7J1MXb5txqMn53wHQ0w&s',
      description: 'How to stabilize a fracture and prepare for professional treatment.',
      instructions: 'If you suspect someone has a fracture, immobilize the affected area immediately to prevent further damage. Use splints, a rolled-up newspaper, or a sturdy object to stabilize the injured limb. Apply ice to the injury site to reduce swelling, but avoid placing the ice directly on the skin. Elevate the injured limb if possible to further reduce swelling. Seek immediate medical attention, as fractures require professional care to ensure proper healing. Avoid trying to realign the bone, as this can cause further harm.'
    },
    {
      videoId: '06WXCWDaJps',  
      title: 'Choking First Aid',
      channel: 'By Safe Life',
      time: '5min',
      rating: 5,
      type: 'Critical',  
      duration: '3 min',
      thumbnail: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS1z_1RjxG3rqV23fpLNjOgj3r3UopT6ClWMQ&s',
      description: 'Life-saving steps for dealing with a choking victim.',
      instructions: 'If a person is choking, encourage them to cough to try and dislodge the object. If they cannot breathe or speak, perform the Heimlich maneuver by applying quick, upward thrusts to their abdomen. For infants, perform back blows and chest thrusts instead. If the person becomes unconscious, begin CPR and check their mouth for any visible obstruction. Continue CPR until emergency medical help arrives or the person starts breathing again. Time is critical in choking situations, so act quickly.'
    },
    {
      videoId: 'YNwqdR0JaqE',  
      title: 'Simple Scrapes Care',
      channel: 'By Emergency Guide',
      time: '8min',
      rating: 3,  
      type: 'Minor',  
      duration: '3 min',
      thumbnail: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTvRCgZpd30l4BOmTscslOr3meZD2JbRcm6gg&s',
      description: 'Learn how to clean and dress small scrapes, but some tips are missing.',
      instructions: 'For small scrapes, wash the affected area with clean water and soap to remove any dirt. Apply an antiseptic solution or ointment to prevent infection. Cover the scrape with a sterile bandage or gauze pad to keep it clean. Change the bandage regularly and monitor for signs of infection, like redness or swelling. While scrapes typically heal on their own, seek medical attention if they don’t improve or if there’s excessive pain or pus.'
    },
    {
      videoId: 'R6VdoV8dZRc',  
      title: 'Heat Stroke Treatment',
      channel: 'By HealthLine',
      time: '40min',
      rating: 5,
      type: 'Critical',  
      duration: '10 min',
      thumbnail: 'https://healthcare.utah.edu/sites/g/files/zrelqx136/files/media/images/2023/GettyImages-1396435926-heat.jpg',
      description: 'Quick and effective steps to treat a person suffering from heat stroke.',
      instructions: 'In case of heat stroke, move the person to a cooler area immediately and remove any excess clothing to help cool them down. Give them cool water to drink if they are conscious, but avoid ice-cold drinks as this can cause shock. Apply cool, wet cloths or use a fan to help lower their body temperature. If the person is unconscious or vomiting, do not give them fluids and seek medical attention immediately. Monitor their breathing, and if they stop breathing, begin CPR. Heat stroke can be life-threatening, so prompt action is crucial.'
    },
    {
      videoId: 'Sf85qfJUNfc',  
      title: 'Hypothermia Treatment',
      channel: 'By First Aid Expert',
      time: '25min',
      rating: 4,
      type: 'Medium',  
      duration: '9 min',
      thumbnail: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQkHZkzN_lHdpa8HSlrB2aOtRL_RRHFC9oTOA&s',
      description: 'How to properly treat hypothermia with first aid and warming techniques.',
      instructions: 'For hypothermia, the first step is to move the person to a warm, dry area to prevent further heat loss. Remove any wet clothing and replace it with dry, warm clothing or blankets. Offer warm (not hot) liquids if the person is conscious and alert. Avoid applying direct heat like heating pads or hot water bottles, as this can cause burns. If the person is unconscious or shows signs of severe hypothermia, seek medical assistance immediately. Monitor their breathing and heart rate, and provide CPR if necessary until help arrives.'
    },
  ];